### ISSUE TITLE
Update example for decoding/encoding Lists

### ISSUE THREAD

**Issue by sheaam30** [stablekernel/dart-codable#3]
`decodeObjectList` doesn't appear to be a part of the API anymore. Could you show how the `decodeObjects` would work instead?

**Comment by itsjoeconway** [comment]
Yikes, I didn't know other people even knew this repo existed. I'll watch the repo from now on. The API will see some breaking changes as it gets integrated into downstream projects.

Is your top-level object a list, or are you decoding an object that contains a list? The former isn't yet supported (AFAIK, you can do `ListArchive.fromRaw`, but that isn't the intended final API). The latter looks like:

```dart
class Container extends Coding {
  List<Element> elements; // Assume Element to extend Coding
  @override
  void decode(KeyedArchive object) {
    super.decode(object);
    elements = object.decodeObjects("elements", () => Element());
  }
}
```

**Comment by itsjoeconway** [comment]
I've updated the README documentation to address this, closing.
