### ISSUE TITLE
Better handling of enums

### ISSUE THREAD

**Issue by enyo** [stablekernel/dart-codable#8]
Right now it's quite difficult to handle enums properly. We have written our own enum implementations that look like this:

```dart
class RecipientType {
  final String id;

  static const to = RecipientType._('to');
  static const cc = RecipientType._('cc');
  static const bcc = RecipientType._('bcc');

  static const values = [to, cc, bcc];

  const RecipientType._(this.id);

  static fromString(String id) => values.firstWhere((type) => type.id == id);
}
```

Encoding/decoding these values is quite verbose, because you need to check for `null` values, and then assign the right enum.

It would be great if there was some support for this.

**Comment by itsjoeconway** [comment]
Can `RecipientType` implement `Codable`? Or do you want to avoid having `RecipientType` altogether and replace with an enum? 

I don't think there is (currently) an effective way of doing this without mirrors. I'm open to suggestions - could you post an example of what you would expect your decode method to look like if this behavior were available?

**Comment by enyo** [comment]
The main reason we didn't want the `RecipientType` to implement `Coding` and use the same strategy, is because the enums are const values and we would like them to remain const. We also wanted to avoid exposing the private constructor.

Now when I have an object that does implement `Coding`, it normally looks like this:

```dart
class Recipient extends Coding {
  String email;
  RecipientType type;

  @override
  decode(KeyedArchive object) {
    super.decode(object);
    email = object.decode('email');
    type = RecipientType.fromString(object.decode('type'));
  }
}
```

This fails if `type` is `null`, that's why we changed the code to:

```dart
  @override
  decode(KeyedArchive object) {
    super.decode(object);
    email = object.decode('email');
    final t = object.decode('type');
    type = t == null ? null : RecipientType.fromString(t);
  }
```

But we then realised that it's best to simply add a `null` check to `RecipientType.fromString` and handle it there... so I think there is nothing this library could do better to handle this.

Thanks for your time.
